<?php

declare(strict_types=1);

use Hyva\GraphqlViewModel\ViewModel\GraphqlViewModel;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\Currency;
use Hyva\Theme\ViewModel\HyvaCsp;
use Hyva\Theme\ViewModel\Store;
use Hyva\Theme\ViewModel\LucideIcons;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

/** @var Escaper $escaper */
/** @var Template $block */
/** @var HyvaCsp $hyvaCsp */
/** @var ViewModelRegistry $viewModels */
/** @var Store $viewModelStore */
/** @var LucideIcons $lucideIcons */
/** @var GraphqlViewModel $gqlViewModel */
/** @var Currency $currencyViewModel */

$storeViewModel = $viewModels->require(Store::class);
$gqlViewModel = $viewModels->require(GraphqlViewModel::class);
$currencyViewModel = $viewModels->require(Currency::class);
$lucideIcons = $viewModels->require(LucideIcons::class);
$gqlRemoveProductsFromWishlistQuery = '
    mutation ($wishlistId: ID!, $itemIds: [ID!]!) {
        removeProductsFromWishlist(wishlistId: $wishlistId, wishlistItemsIds: $itemIds) {
            wishlist {
                items_count
            }
        }
    }
';
$gqlProductsQuery = '
    query ($query: String!) {
        products(search: $query) {
            items {
                id
                sku
                name
                thumbnail {
                    url
                }
                price_range {
                    minimum_price {
                        final_price {
                            value
                        }
                    }
                }
            }
        }
    }
';
?>

<script>
    function initWishlistDrawer() {
        return {
            open: false,
            isLoading: false,
            wishlistItems: [],
            wishlist: null,
            searchItems: [],
            query: '',
            itemsCount: 0,

            productIsVisibleInSite() {
                return !!this.item.product_is_saleable_and_visible;
            },

            productIsNotVisibleInSite() {
                return !this.productIsVisibleInSite();
            },

            wishlistIsEmpty() {
                return this.itemsCount === 0;
            },

            searchQueryIsEmpty() {
                return !this.query.trim();
            },

            closeWishlistDrawer() {
                this.open = false;
            },

            getItemQty() {
                const params = JSON.parse(this.item.add_to_cart_params);
                return +params.data.qty || 1;
            },

            getWishlistItemId() {
                const params = JSON.parse(this.item.add_to_cart_params);
                return +params.data.item;
            },

            getConfigureUrl() {
                const { product_id: id } = this.item;
                const itemId = this.getWishlistItemId();
                const qty = this.getItemQty();

                return BASE_URL + `wishlist/index/configure/id/${itemId}/product_id/${id}/qty/${qty}/`
            },

            getData() {
                const data = this.$event.detail.data;

                if (data.wishlist_full) {
                    this.wishlist = data.wishlist_full;
                    this.itemsCount = this.wishlist.items && this.wishlist.items.length || 0;
                    this.setWishlistItems();
                }
                this.isLoading = false;
            },

            setWishlistItems() {
                this.wishlistItems = this.wishlist.items && this.wishlist.items.sort((a, b) => b.item_id - a.item_id) || [];
            },

            productAriaLabel() {
                return hyva.strf(this.$el.dataset.ariaLabel, this.item.product_name)
            },

            finalPrice() {
                return hyva.formatPrice(this.item.price_range.minimum_price.final_price.value, false);
            },

            async removeProductsFromWishlist() {
                const query = `<?= /** @noEscape */ $gqlViewModel->query('removeProductsFromWishlistQuery', $gqlRemoveProductsFromWishlistQuery) ?>`;
                const variables = {
                    wishlistId: this.wishlist.wishlist_id,
                    itemIds: [this.getWishlistItemId()]
                };

                this.isLoading = true;
                const response = await hyvaWishlistGraphql('POST', query, variables);
                this.isLoading = false;
                if (response.ok) {
                    window.dispatchEvent(
                        new CustomEvent('reload-customer-section-data', {
                            detail: { sections: ['wishlist', 'wishlist_full'] }
                        })
                    );
                }
            },

            async search() {
                this.query = this.$event.target.value.trim();
                if (!this.query) {
                    return;
                }

                const query = `<?= /** @noEscape */ $gqlViewModel->query('productsQuery', $gqlProductsQuery) ?>`;
                const variables = {
                    query: this.query
                };

                const response = await hyvaWishlistGraphql('POST', query, variables);
                if (!response.ok) {
                    return;
                }

                const result = await response.json();
                this.searchItems = result.data.products.items;
            },

            eventListeners: {
                ['@private-content-loaded.window'](event) {
                    this.getData(event.detail.data);
                },
                ['@toggle-wishlist.window'](event) {
                    this.open = !!event.detail.isOpen;
                },
            }
        }
    }

    window.addEventListener('alpine:init', () => {
        Alpine.data('initWishlistDrawer', initWishlistDrawer);
    }, { once: true });

    async function hyvaWishlistGraphql(method = 'GET', query, variables) {
        try {
            return await fetch(BASE_URL + 'graphql', {
                method,
                headers: {
                    'Store': '<?= $escaper->escapeJs($storeViewModel->getStoreCode()) ?>',
                    'Content-Currency': '<?= $escaper->escapeJs($currencyViewModel->getCurrentCurrencyCode()) ?>',
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({
                    query,
                    variables
                })
            });
        } catch (error) {
            console.log(error);
        }

        return null;
    }
</script>
<?php $hyvaCsp->registerInlineScript() ?>

<dialog
    id="wishlist-drawer"
    aria-labelledby="wishlist-drawer-title"
    class="w-[480px] md:w-[640px] h-full max-h-full me-0 open:flex flex-col transition ease-out duration-300 motion-reduce:duration-0 rounded-e-none"
    x-data="initWishlistDrawer"
    x-bind="eventListeners"
    x-show="open"
    x-htmldialog="closeWishlistDrawer"
    closeby="any"
    x-transition:enter="transition ease-in-out duration-500"
    x-transition:enter-start="translate-x-full"
    x-transition:enter-end="translate-x-0"
    x-transition:leave="transition ease-in-out duration-300"
    x-transition:leave-start="translate-x-0"
    x-transition:leave-end="translate-x-full"
>
    <?= $block->getChildHtml('wishlist-drawer.top'); ?>

    <div class="flex gap-2 justify-between items-center">
        <p id="wishlist-drawer-title" class="text-2xl">
            <strong><?= $escaper->escapeHtml(__('My Wishlist')) ?></strong>
            <span class="items-total text-xs"></span>
        </p>
        <button
            type="button"
            class="btn bg-transparent border-transparent p-2"
            @click="closeWishlistDrawer"
            aria-label="<?= $escaper->escapeHtmlAttr(__('Close wishlist')) ?>"
        >
            <?= $lucideIcons->xHtml('', 24, 24, ['aria-hidden' => 'true']); ?>
        </button>
    </div>

    <?= $block->getChildHtml('wishlist-drawer.items.before'); ?>

    <template x-if="searchQueryIsEmpty">
        <div class="contents">
            <template x-if="wishlistIsEmpty">
                <div class="grow grid place-items-center">
                    <div class="text-center">
                        <?= $lucideIcons->heartPlusHtml('inline-block text-fg/30 max-w-full h-auto', 120, 120, ['aria-hidden' => 'true']); ?>
                        <p class="mt-10 text-xl">
                            <strong><?= $escaper->escapeHtml(__('Wishlist is empty')) ?></strong>
                        </p>
                    </div>
                </div>
            </template>

            <template x-if="itemsCount">
                <ul class="grow flex flex-col overflow-y-auto overscroll-y-contain mask-overflow mask-dir-y">
                    <template x-for="item in wishlistItems">
                        <?= /** @noEscape */ $block->getChildHtml('wishlist-item'); ?>
                    </template>
                </ul>
            </template>
        </div>
    </template>

    <?= $block->getChildHtml('wishlist-drawer.bottom'); ?>

    <template x-if="itemsCount">
        <div>
            <div class="flex flex-col gap-y-4 mt-8">
                <a
                    href="<?= $escaper->escapeUrl($block->getUrl('wishlist')) ?>"
                    class="btn btn-secondary"
                >
                    <?= $escaper->escapeHtml(__('View and Edit Wishlist')) ?>
                </a>
                <?= $block->getChildHtml('extra_actions'); ?>
            </div>
        </div>
    </template>

    <template x-if="wishlistIsEmpty">
        <div class="flex flex-col">
            <button
                type="button"
                @click="closeWishlistDrawer"
                class="btn btn-primary"
            ><?= $escaper->escapeHtml(__('Continue Shopping')) ?></button>
        </div>
    </template>

    <?= $block->getChildHtml('loading') ?>
</dialog>
